.TH "ASC2XML" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
asc2xml \- convert &#nnn; entities to UTF-8
.SH SYNOPSIS
.B asc2xml
.SH DESCRIPTION
.LP
Reads an ASCII or ISO-8859-1 (Latin-1) text from standard input and
writes encoded UTF-8 to standard output.
.SH "SEE ALSO"
.BR xml2asc (1),
.BR UTF-8 " (RFC 2279)"
