.TH "HXCOUNT" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxcount \- count elements and attributes in HTML or XML files
.SH SYNOPSIS
.B hxcount
.RI "[\| " file-or-URL " \|]"
.SH DESCRIPTION
.LP
The
.B hxcount
command counts the number of elements and attributes of each type that
appears in the input and prints a report on stdout.
.SH OPERANDS
The following operand is supported:
.TP 10
.I file-or-URL
The name or URL of an HTML or XML file. If absent, standard input is read
instead.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B > 0
An error occurred in the parsing of the HTML or XML file.
.B hxcount
will try to recover from the error and produce output anyway.
.SH ENVIRONMENT
To use a proxy to retrieve remote files, set the environment variables
.B http_proxy
and
.BR ftp_proxy "."
E.g.,
.B http_proxy="http://localhost:8080/"
.SH BUGS
.LP
Don't trust the output if there were errors in the input.
.LP
Remote files (specified with a URL) are currently only supported for
HTTP. Password-protected files or files that depend on HTTP "cookies"
are not handled. (You can use tools such as
.BR curl (1)
or
.BR wget (1)
to retrieve such files.)
.SH "SEE ALSO"
.BR asc2xml (1),
.BR hxprune (1),
.BR hxnormalize (1),
.BR hxnum (1),
.BR hxtoc (1),
.BR hxunent (1),
.BR xml2asc (1),
.BR UTF-8 " (RFC 2279)"
