.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXMULTITOC" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxmultitoc \- create a table of content for a set of HTML files
.SH SYNOPSIS
.B hxmultitoc
.RB "[\| " \-x " \|]"
.RB "[\| " \-s
.IR preample " \|]"
.RB "[\| " \-e
.IR postample " \|]"
.RB "[\| " \-l
.IR low
.RB " | " \-h
.IR high
.RB " | " \-b
.IR base
.RB " | " \-c
.IR configfile
.RI " | " file " \|] ..."
.SH DESCRIPTION
[ToDo]
