.TH "HXNSXML" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxnsxml \- convert output of hxxmlns back to XML
.SH SYNOPSIS
.B hxnsxml
.RI "[\| " file " \|]"
.SH DESCRIPTION
.B hxnsxml
looks for element and attribute names that start with an XML Namespace
in curly braces and converts them into normal element and attribute
names paired with an xmlns attribute. E.g.,
<{http://example.org/foo}bar> is converted to
<bar xmlns="http://example.org/foo">
.SH "DIAGNOSTICS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B > 0
An error occurred in the parsing of the XML file.
.B hxnsxml
will try to correct the error and produce output anyway.
.SH "SEE ALSO"
.BR hxxmlns (1),
