.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXPRINTLINKS" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxprintlinks \- add a numbered list of links at the end of an HTML file
.SH SYNOPSIS
.B hxprintlinks
.RB "[\| " \-b
.IR base " \|]"
.I file-or-URL
.SH DESCRIPTION
.B hxprintlinks
adds a numbered list of all URLs (links) found in the file to the end of
the HTML file.
.SH OPTIONS
The following options are supported:
.TP
.BI \-b " base"
Make the URLs in the list absolute, using
.I base
as the base URL.
.SH OPERANDS
The following operand is supported:
.TP
.I file-or-URL
The file to work on. If the argument is absent, or if it is - (a
single dash), the document is read from the standard input.
.SH "SEE ALSO"
.BR hxcopy (1)
.SH BUGS
.LP
The option
.B \-b
is probably of limited use. It makes the links in the generated list
absolute, but doesn't change the other links. For a more flexible
solution, use
.BR hxcopy (1)
on the output of
.BR hxprintlinks .
E.g., instead of
.d
hxprintlinks -b http://example.org/base/ myfile.html
.e
use
.d
hxprintlinks myfile.html | hxcopy -i http://example.org/base -o .
.e
