.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXTOC" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxtoc \- insert a table of contents in an HTML file
.SH SYNOPSIS
.B hxtoc
.RB "[\| " \-x " \|]"
.RB "[\| " \-l
.IR low " \|]"
.RB "[\| " \-h
.IR high " \|]"
.RB "[\| " \-t " \|]"
.RB "[\| " \-d " \|]"
.RB "[\| " \-c
.IR class " \|]"
.RB "[\| " \-f " \|]"
.RI "[\| " file-or-URL " \|]"
.SH DESCRIPTION
.LP
The
.B hxtoc
command reads an HTML file, inserts missing ID attributes in all H1 to
H6 elements between the levels
.B \-l
and
.B \-h
(unless the option
.B \-d
is in effect, see below). Unless the option
.B \-t
is given, it also inserts A elements with NAME attributes, because old
browsers do not recognize ID attributes as target anchors. The output
is written to stdout.
.LP
If there is a comment of the form
.d
<!\-\-toc\-\->
.e
or a pair of comments
.d
<!\-\-begin-toc\-\->
\&...
<!\-\-end-toc\-\->
.e
then the comment, or the pair with everything in between, will be
replaced by a table of contents, consisting of a list (UL) of links to
all headers in the document.
.LP
The text of headers is copied to this table of contents, including any
inline markup, except that ID attributes, DFN tags and SPAN tags with
a CLASS of "index" are omitted (but the elements' content is copied).
.LP
The copied text can optionally be "flattened" first, see option
.BR \-f .
.LP
If a header has a CLASS attribute with as value (or one of its values)
the keyword "no-toc", then that header will not appear in the table
of contents.
.SH OPTIONS
The following options are supported:
.TP 10
.B \-x
Use XML conventions: empty elements are written with a slash at the
end: <IMG\ />
.TP
.BI \-l " low"
Sets the lowest numbered header to appear in the table of
content. Default is 1 (i.e., H1).
.TP
.BI \-h " high"
Sets the highest numbered header to appear in the table of
content. Default is unlimited.
.TP
.B \-t
Normally,
.B hxtoc
adds both ID attributes and empty A elements with a NAME attribute and
CLASS="bctarget", so that older browsers that do no understand ID will
still find the target. With this option, the A elements will not be
generated.
.TP
.BI \-c " class"
The generated UL elements in the table of contents will have a CLASS
attribute with the value
.I class.
The default is "toc".
.TP
.B \-d
Tries to use sectioning elements as targets in the table of contents
instead of H1 to H6. A sectioning elements is a DIV, SECTION, ARTICLE,
ASIDE or NAV element that contains at least one heading element (H1 to
H6) or HGROUP. The sectioning element will be given an ID if it
doesn't have one yet. With this option, the level of any H1 to H6 that
is the first heading of a sectioning element is not determined by its
name, but by the nesting depth of the sectioning elements. (Any H1 to
H6 that are not the first heading of a sectioning element still have
their level implied by their name.)
.TP
.B \-f
Flatten the text of the table of contents. Without
.BR \-f ,
the contents of header elements are copied to the table of contents
almost unchanged, i.e., including any child elements and their
attributes (except for ID attributes, DFN elements and certain SPAN
elements, as explained above). With
.BR \-f ,
the contents are flattened instead: All child elements are removed and
only their contents are copied to the table of contents. Additionally
elements with an ALT attribute, such as IMG, are replaced by the
contents of the ALT attribute. Exception: BDO tags are copied
unchanged and elements with a DIR attribute are replaced by a SPAN
with that DIR attribute. (BDO and DIR may occur in languages written
right-to-left.)
.SH OPERANDS
The following operand is supported:
.TP 10
.I file-or-URL
The name or URL of an HTML file. If absent, standard input is read instead.
.SH "DIAGNOSTICS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B > 0
An error occurred in the parsing of the HTML file.
.B hxtoc
will try to correct the error and produce output anyway.
.SH "SEE ALSO"
.BR asc2xml (1),
.BR hxnormalize (1),
.BR hxnum (1),
.BR xml2asc (1)
.SH BUGS
.LP
The error recovery for incorrect HTML is primitive.
