.TH "HXUNCDATA" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxuncdata \- replace CDATA sections by character entities
.SH SYNOPSIS
.B hxuncdata
.RI "[\| " xml-file " \|]"
.SH DESCRIPTION
.B hxuncdata
replaces CDATA sections by character entities. The input is scanned
for occurrences of "<![CDATA[" and corresponding "]]>". Those strings
are removed and all occurrences of "&", "<" and ">" in between them
will be replaced by "&amp;", "&lt;" and "&gt;" respectively.
.PP
The input must be 1 byte per character. If it is not, convert it to
UTF-8 first.
.SH OPTIONS
The following options are supported:
.TP
.BR \-? ", " \-\-help
Show command usage.
.SH OPERANDS
The following operand is supported:
.TP
.I xml-file
The file to work on.
.SH SEE ALSO
.BR UTF-8 " (RFC 2279)"
