.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXUNPIPE" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxunpipe \- convert output of hxpipe back to XML format
.SH SYNOPSIS
.B hxunpipe
.RB "[\| " \-b " \|]"
.RI "[\| " file-or-URL " \|]"
.SH DESCRIPTION
.B hxunpipe
takes the output of
.BR hxpipe (1)
(or of 
.BR onsgmls (1))
and turns it back into XML/SGML mark-up.
.SH OPTIONS
The following options are supported:
.TP 10
.B \-b
Normally,
.B hxunpipe
assumes the input was made by hxpipe, i.e., the
input may contain character entities but will never contain SGML/XML
delimiters (<>&"') that need to be escaped. When the input was made by
(o)nsgmls, however, the entities will have been expanded and the input
may contain SGML/XML delimiters. The option
.B \-b
causes
.B hxunpipe
to look for those delimiters and escape them: "<" as "&lt;", ">" as
"&gt;", "&" as "&amp;", """ as "&quot;" and "'" as "&apos;".
.SH OPERANDS
The following operand is supported:
.TP 10
.I file-or-URL
The name or URL of an HTML file. If absent, standard input is read
instead.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B > 0
An error occurred in the input.
.SH ENVIRONMENT
To use a proxy to retrieve remote files, set the environment variables
.B http_proxy
and
.BR ftp_proxy "."
E.g.,
.B http_proxy="http://localhost:8080/"
.SH BUGS
.LP
Not all syntax errors in the input are recognized.
.LP
.B hxunpipe
can currently only retrieve remote files over HTTP. It doesn't handle
password-protected files, nor files whose content depends on HTTP
"cookies."
.SH "SEE ALSO"
.BR hxpipe (1),
.BR onsgmls (1).
