.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXUNXMLNS" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxunxmlns \- replace XML "global names" by Namespace prefixes
.SH SYNOPSIS
.B hxunxmlns
.RB "[\| " \-\- " \|]"
.RI "[\| " file " \|]"
.SH DESCRIPTION
.B hxunxmlns
is the reverse of
.BR hxxmlns (1).
It converts element and attribute names of the form
.d
<{URL1}foo {URL2}bar="...">
.e
to
.d
<foo xmlns="URL1" xmlns:x="URL2" x:bar="...">
.e
.PP
The predefined XML Namespace is recognized and replaced by the prefix "xml:".
.SH "DIAGNOSTICS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B > 0
One or more errors occurred in the parsing of the file.
.SH "SEE ALSO"
.BR hxxmlns (1)
.SH BUGS
.LP
The error recovery for incorrect XML is primitive.
