.TH "HXXMLNS" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxxmlns \- replace XML Namespace prefixes by "global names"
.SH SYNOPSIS
.B hxxmlns
.RB "[\| " \-d " \|]"
.RB "[\| " \-\- " \|]"
.RI "[\| " file " \|]"
.SH DESCRIPTION
.B hxxmlns
expands all element and attribute names to "global names" by expanding
the prefix. All names will be printed as "{URL}name". Attribute names
without a prefix will have an empty namespace part: "{}name". The
namespace attributes (those that start with "xmlns") will be removed.
.PP
By default comments, PIs and the DOCTYPE declaration are copied unchanged,
but with option
.B \-d
they are removed.
.PP
[ToDo]
